version: "3"
 
services:
  mysicuel:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=codeigniter_test
      - MYSQL_ROOT_PASSWORD=ale
      - MYSQL_USER=ale
      - MYSQL_PASSWORD=ale
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - siteweb
    container_name: mysicuel
    restart: always
  apaches:
    build: 
      context: 'deploy/apache'
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./public_html/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links: 
      - mysicuel
    container_name: apaches
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysicuel
    image: phpmyadmin/phpmyadmin
    restart: always
    expose: 
      - 8080
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - siteweb
    volumes:
     - ./volumenes/phpmyadmin/session/:/session/
     - ./volumenes/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
     - ./volumenes/phpmyadmin/theme/:/www/themes/theme/

networks: 
  siteweb: